### ISSUE TITLE
Installation error when running melos bs

### ISSUE THREAD

**Issue by jeff9315** [JLogical-Apps/flood#8]
I assume it's when git is trying to get to your repository. Since I'm so new, I don't know whether I did something wrong.

```
Git error. Command: `git clone --mirror git@github.com:JLogical-Apps/flood.git C:\Users\jeff\AppData\Local\Pub\Cache\_temp\dir98ad0441`
stdout:
stderr: Cloning into bare repository 'C:\Users\jeff\AppData\Local\Pub\Cache\_temp\dir98ad0441'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
exit code: 128
BootstrapException: Failed to install.: todo at l:\flutterapps\2024-restart\todo\todo.
```

**Comment by jaboyc** [comment]
Hi @jeff9315, 

The error you're seeing is related to SSH authentication failing when trying to clone the repository. This can happen if you don't have SSH keys set up with your GitHub account or if there are issues with your SSH configuration. Here are a couple of ways to resolve this:

## ~~1. Use HTTPS Instead of SSH URLs (Quickest Solution)~~
**Edit: Do not use this method. Flood uses SSH URLs internally, so this approach will not work.**

The simplest way to resolve this issue is to use HTTPS URLs instead of SSH URLs. To do this:

1. Open your `pubspec.yaml` file.
2. Find the `url` parameters for `flood`, `flood_core`, and `flood_cli`.
3. Change the URLs from `git@github.com:JLogical-Apps/flood.git` to `https://github.com/JLogical-Apps/flood.git`.

For example, you can change [this](https://github.com/JLogical-Apps/flood-example/blob/v4.2/todo_core/pubspec.yaml#L11-L20) to 
```yaml
  flood_core:
    git:
      url: "https://github.com/JLogical-Apps/flood.git"
      ref: v4.2
      path: packages/flood/flood_core
  flood_cli:
    git:
      url: "https://github.com/JLogical-Apps/flood.git"
      ref: v4.2
      path: packages/flood/flood_cli
```

Don't forget to also update the dependency in the `app` project: https://github.com/JLogical-Apps/flood-example/blob/v4.2/todo/pubspec.yaml#L11

Using HTTPS doesn't require SSH keys and is often easier for beginners.

## 2. Add an SSH Key to Your GitHub Account (Recommended for Long-term Use)

If you prefer using SSH (which is more secure), you can set up SSH keys:

1. Generate a new SSH key:
   https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

2. Add the SSH key to your GitHub account:
   https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

Let me know if you run into any more issues! Will close for now.
